### ISSUE TITLE
Develop SD storage code + Wiring Diagram (Arduino Side)

### ISSUE THREAD

**Issue by Z-Ranster** [Z-Ranster/WM_Baja_DA#4]
**ToDo:**
- [ ] Develop SD data storage structure (make sure to document this in the code) --> @gabsillis 
- [ ] Develop SD storage code --> @gabsillis 
-- Make it so we can open the SD data in an excel file, basic matlab script, or java script
- [ ] Develop wiring diagram for SD shield --> @Z-Ranster

**Comment by gabsillis** [comment]
Itead Studio sd shield 2.0

**Comment by gabsillis** [comment]
https://code.google.com/archive/p/arduino-filelogger/
