### ISSUE TITLE
Brain - Develop Initial Desktop Code

### ISSUE THREAD

**Issue by Z-Ranster** [Z-Ranster/WM_Baja_DA#5]
**ToDo:**
- [x] Decide which software to use (Java) --> However we may need to use Matlab b/c Justin wants it
- [ ]  Map out requirements and basic code structure (put the code in the Github\WM_Baja_DA\Offboard folder)
- [ ] Locate graph libraries
