### ISSUE TITLE
Initial RPM System Development

### ISSUE THREAD

**Issue by Z-Ranster** [Z-Ranster/WM_Baja_DA#6]
**ToDo:**
- [x] Write measuring code for Arduino - @gabsillis 
- [ ] Add code to save the measurement to the SD card --> Moved to a diffent issue
- [x] Add code to desktop app to view measurements
