### ISSUE TITLE
Design magnet mounts for primary + secondary

### ISSUE THREAD

**Issue by Z-Ranster** [Z-Ranster/WM_Baja_DA#7]
**ToDo:**
- [x] Source magnets
- [x] Build magnet mounts for both the primary and secondary (determine the mount locations)
- [x] Tell @Z-Ranster so he can add them to the final assembly

**Comment by Z-Ranster** [comment]
Currently in progress. Need to focus on sourcing all of the necessary hardware. Also, need to add all of the mounting hardware + plastic cover + basic electrical hardware model to the model.

**Comment by Z-Ranster** [comment]
Most updated.
- [x] Add something to keep the sensor Polycarb closed
- [x] Add cutouts for wires
