### ISSUE TITLE
CVT-RPM - HardwareSourcing/BOM Updates

### ISSUE THREAD

**Issue by Z-Ranster** [Z-Ranster/WM_Baja_DA#8]
**ToDo:**
- [ ] Source wires + connectors for RPM tracking
- [ ] Source Hall effect sensor (add to BOM)
- [ ] Source magnet (add to BOM)
- [ ] Source wires + connectors for temperature tracking (add to BOM)
